### ISSUE TITLE
No prompt for the password, then an error

### ISSUE THREAD

**Issue by ppom0** [muxueqz/git-credential-pass#1]
Hi, I followed the instructions :
The `.py` is in my `$PATH`, the `.ini` is filled in my `~/.config`,
and I executed this :
`git config --global credential.helper git-credential-pass.py`

When I attempt a `git push` on a git project, git throw me this error :
```
$ git push
git: 'credential-git-credential-pass.py' is not a git command. See 'git --help'.
```
The `.ini` configuration is omitted in your `README`.
Did you forgot another command ?
Thanks,
ppom

**Comment by muxueqz** [comment]
Hello aopom
Can you try to run this command?
```
echo host=[Your git repo domain, like github.com] | git-credential-pass.py get
```

My result is :
```bash
$ echo host=github.com | git-credential-pass.py get
username=muxueqz
password=something
```

Maybe you need to `chmod +x git-credential-pass.py`

**Comment by ppom0** [comment]
Thanks for your quick reply :)
```sh
$ echo host=github.com | git-credential-pass.py get
gpg: decryption failed: No secret key
Traceback (most recent call last):
  File "/usr/local/bin/git-credential-pass.py", line 59, in <module>
    find_path,
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['pass', 'show', 'i/github']' returned non-zero exit status 2
```
It seems that the gpg process can't ask for my password.
In my environment, the password is asked on the terminal, using a TUI.
Is it asked using a GUI on your environment ? I believe this divergence is the origin of the problem.

**Comment by muxueqz** [comment]
I use a TUI too, but i will run `pass ls XXX` in an other terminal before  .

About the point , I have the same problem, But for the time being , there is no better solution, maybe i can run a damon to pop-up a window ask my password

**Comment by muxueqz** [comment]
I just push a new version, can you try ?

**Comment by ppom0** [comment]
Thanks a lot ! Now I have this part working :
```shell
$ echo host=github.com | git-credential-pass.py get
username=aopom
password=something
```
but this does not work :
```shell
$ git push
git: 'credential-git-credential-pass.py' is not a git command. See 'git --help'.
```
I think that you solved the problem but I have a configuration issue.
Are you sure of your config steps ?
Thanks again.

**Comment by muxueqz** [comment]
Can you show me the git config?

my config:
```
$ git config -l | grep cre
credential.helper=/opt/muxueqz-py/git-credential-pass.py
```

**Comment by ppom0** [comment]
I achieved it providing the full path of the command, like you did. Thanks.
It's now working !
Maybe you should tell in the readme that the full path is needed :)
Thank you

**Comment by muxueqz** [comment]
You are welcome
I've updated the readme already
